server {
    # Nginx מקשיב על פורט 80 (HTTP רגיל)
    listen 80;

    # כל הבקשות (כולל static) - מעביר לשרת Flask שרץ בקונטיינר "app" על פורט 5000
    location / {
        proxy_pass http://app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr; 
    }
}
